/** @type {import('tailwindcss').Config} */

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    container: {
      center: true,
    },
    extend: {
      colors: {
        green: {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#14532d',
        },
        theme: {
      bg: 'var(--color-bg)',
      bgSecondary: 'var(--color-bg-secondary)',
      bgCard: 'var(--color-bg-card)',
      bgHover: 'var(--color-bg-hover)',
      text: 'var(--color-text)',
      textSecondary: 'var(--color-text-secondary)',
      textMuted: 'var(--color-text-muted)',
      accent: 'var(--color-accent)',
      accentHover: 'var(--color-accent-hover)',
      accentLight: 'var(--color-accent-light)',
      border: 'var(--color-border)',
      borderLight: 'var(--color-border-light)',
      success: 'var(--color-success)',
      warning: 'var(--color-warning)',
      danger: 'var(--color-danger)',
      scrollbar: 'var(--color-scrollbar)',
      bgSecondaryMuted: 'var(--color-bg-secondary-muted)',
      bgSecondarySubtle: 'var(--color-bg-secondary-subtle)',
      bgCardMuted: 'var(--color-bg-card-muted)',
      bgCardLight: 'var(--color-bg-card-light)',
      bgCardSubtle: 'var(--color-bg-card-subtle)',
      bgCardFaint: 'var(--color-bg-card-faint)',
      bgCardHoverLight: 'var(--color-bg-card-hover-light)',
      bgBottomNav: 'var(--color-bg-bottom-nav)',
      bgBottomNavLight: 'var(--color-bg-bottom-nav-light)',
      bgCardVeryFaint: 'var(--color-bg-card-very-faint)',
      bgCardExtraFaint: 'var(--color-bg-card-extra-faint)',
      bgSecondaryLight: 'var(--color-bg-secondary-light)',
    },
  },
},
  },
  plugins: [],
};